INSERT INTO category (descriptions) VALUES ('American');
INSERT INTO category (descriptions) VALUES ('Italian');
INSERT INTO category (descriptions) VALUES ('Mexican');
INSERT INTO category (descriptions) VALUES ('Fast Food');
INSERT INTO unit_of_measure (descriptions) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (descriptions) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (descriptions) VALUES ('Cup');
INSERT INTO unit_of_measure (descriptions) VALUES ('Pinch');
INSERT INTO unit_of_measure (descriptions) VALUES ('Ounce');
INSERT INTO unit_of_measure (descriptions) VALUES ('Each');
INSERT INTO unit_of_measure (descriptions) VALUES ('Dash');